/******************************************************************************
* Title: TI DSP Dev Tool - Main Source File
* Author: Mike Schoonover
* Date: 06/4/11
*
* Purpose:
*
* This program compiles, links, and simulates Texas Instruments (T)(R) DSP
* code.
*
* 6/4/11
*  Handles TI TMS320C5441 DSP.
*
* Open Source Policy:
*
* This source code is Public Domain and free to any interested party.  Any
* person, company, or organization may do with it as they please.
*
*/

//-----------------------------------------------------------------------------

package tidspdevtool;


import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.DecimalFormat;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
// class MainWindow
//
// Creates a main window JFrame.  Creates all other objects needed by the
// program.
//
// Listens for events generated by the main window.  Calls clean up functions
// on program exit.
//

class MainWindow implements  WindowListener, ActionListener, ChangeListener,
                                ComponentListener, DocumentListener{

Globals globals;
Project project;

JFrame mainFrame;
JDialog measureDialog;
GridBagLayout gridBag;

int initialWidth, initialHeight;

DecimalFormat[] decimalFormats;

//-----------------------------------------------------------------------------
// MainWindow::MainWindow (constructor)
//

public MainWindow()
{

}//end of MainWindow::MainWindow (constructor)
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// MainWindow::init
//
// Call this after construction to setup the object
//

public void init()
{

    //turn off default bold for Metal look and feel
    UIManager.put("swing.boldMetal", Boolean.FALSE);

    //force "look and feel" to the System's default style
    // getCrossPlatformLookAndFeelClassName() -- this is the "Metal" look
    // getSystemLookAndFeelClassName() -- uses the look from the System
    //   (the System style matches Windows, Mac, Linux, etc.)

    try {
        UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
        }
    catch (Exception e) {}

    //makes sure all frames are created with the look and feel specified above
    JFrame.setDefaultLookAndFeelDecorated(true);

    //load globals, project file, and all other settings
    loadSettings();

    //create various decimal formats
    decimalFormats = new DecimalFormat[1];
    decimalFormats[0] = new  DecimalFormat("0000000");

    // Add internal frame to desktop
    JDesktopPane desktop = new JDesktopPane();
    desktop.setOpaque(true);
    desktop.setBackground(Color.LIGHT_GRAY);

    //create the program's main window
    mainFrame = new JFrame("TI DSP Dev Tool");
    mainFrame.addComponentListener(this);
    mainFrame.addWindowListener(this);

    mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    //add the desktop panel to the main frame
    //the desktop panel handles child windows such that and IDE can be created
    mainFrame.getContentPane().add(desktop, BorderLayout.CENTER);
    Globals.setSizes(mainFrame, 1024, 725);

    //create a main menu, passing globals as the object to be installed as
    //the action and item listener for the menu
    //mainFrame.setJMenuBar(mainMenu = new MainMenu(globals));

    mainFrame.setVisible(true);

    //store the height and width of the main window after it has been set up so
    //it can be restored to this size if an attempt is made to resize it
    initialWidth = mainFrame.getWidth();
    initialHeight = mainFrame.getHeight();

    // Create an internal frame
    boolean resizable = true;
    boolean closeable = true;
    boolean maximizable  = true;
    boolean iconifiable = true;

    int width, height;

    ProjectFrame pFrame =
        new ProjectFrame("Project", resizable, closeable, maximizable,
            iconifiable, globals);

    pFrame.init();

    // set an initial size for the project window
    width = 200; height = 500; pFrame.setSize(width, height);

    // by default, internal frames are not visible; make it visible
    pFrame.setVisible(true);

    desktop.add(pFrame);

    //force layout so location and width of the project window can be retrieved
    mainFrame.pack();

    int editorWindowX = pFrame.getX() + pFrame.getWidth();

    String title = "Editor";
    EditorFrame eFrame =
        new EditorFrame(title, resizable, closeable, maximizable, iconifiable);
    eFrame.init();

    // position the editor window just right of the project window
    eFrame.setLocation(new Point(editorWindowX, 0));

    // set an initial size for the editor window
    width = 1000; height = 680; eFrame.setSize(width, height);

    // by default, internal frames are not visible; make it visible
    eFrame.setVisible(true);

    desktop.add(eFrame);

    eFrame.loadFile(
                "Capulin UT DSP.asm", "ASM Source Files//Capulin UT DSP.asm");

    eFrame.loadFile("Documentation.txt", "ASM Source Files//Documentation.txt");

    //force layout of GUI
    mainFrame.pack();

    //force garbage collection before beginning any time sensitive tasks
    System.gc();

}//end of MainWindow::init
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// MainWindow::loadSettings
//
// loads global values, project file, and all other settings required upon
// program startup.
//

private void loadSettings()
{

    globals = new Globals();

    project = new Project(globals);

    globals.sourceCodeFileList = project.sourceCodeFileList.fileList;
    globals.linkerFileList = project.linkerFileList.fileList;
    globals.docFileList = project.docFileList.fileList;

}//end of MainWindow::loadSettings
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// MainWindow::actionPerformed
//
// Responds to button events.
//

@Override
public void actionPerformed(ActionEvent e)
{


}//end of MainWindow::actionPerformed
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// MainWindow::stateChanged
//
// Responds to value changes in spinners, etc.
//
// You can tell which item was changed by using similar to:
//
// Object source = e.getSource();
//
// For simplicities sake, the following just updates all controls any time any
// one control is changed.
//

@Override
public void stateChanged(ChangeEvent e)
{


}//end of MainWindow::stateChanged
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// MainWindow::(various component listener functions)
//
// These functions are implemented per requirements of interface
// ComponentListener but do nothing at the present time.  As code is added to
// each function, it should be moved from this section and formatted properly.
//

@Override
public void componentHidden(ComponentEvent e){}
@Override
public void componentShown(ComponentEvent e){}
@Override
public void componentMoved(ComponentEvent e){}
@Override
public void componentResized(ComponentEvent e){}

//end of MainWindow::(various component listener functions)
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// MainWindow::insertUpdate
//
// Responds to value changes in text areas and fields, specifically when a
// character is inserted. NOTE: This will get called after EVERY character
// inserted - updateAllSettings will get called every time but this shouldn't
// be a problem.
//

@Override
public void insertUpdate(DocumentEvent ev)
{

}//end of MainWindow::insertUpdate
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// MainWindow::removeUpdate
//
// Responds to value changes in text areas and fields, specifically when a
// character is removed. NOTE: This will get called after EVERY character
// removed - updateAllSettings will get called every time but this shouldn't
// be a problem.
//

@Override
public void removeUpdate(DocumentEvent ev)
{

}//end of MainWindow::removeUpdate
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// MainWindow::changedUpdate
//
// Responds to value changes in text areas and fields, specifically when the
// style of the text is changed.
//

@Override
public void changedUpdate(DocumentEvent ev)
{

}//end of MainWindow::changedUpdate
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// MainWindow::windowClosing
//
// Handles actions necessary when the window is closing
//

@Override
public void windowClosing(WindowEvent e)
{

    project.saveFile();

}//end of MainWindow::windowClosing
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// MainWindow::(various window listener functions)
//
// These functions are implemented per requirements of interface WindowListener
// but do nothing at the present time.  As code is added to each function, it
// should be moved from this section and formatted properly.
//

@Override
public void windowActivated(WindowEvent e){}
@Override
public void windowDeactivated(WindowEvent e){}
@Override
public void windowOpened(WindowEvent e){}
//@Override
//public void windowClosing(WindowEvent e){}
@Override
public void windowClosed(WindowEvent e){}
@Override
public void windowIconified(WindowEvent e){}
@Override
public void windowDeiconified(WindowEvent e){}

//end of MainWindow::(various window listener functions)
//-----------------------------------------------------------------------------

}//end of class MainWindow
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------s

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
// class Main
//

public class Main{

//-----------------------------------------------------------------------------
// Main::createAndShowGUI
//
// Create the GUI and show it. For thread safety, this method should be invoked
// from the event-dispatching thread.  This is usually done by using
// invokeLater to schedule this funtion to be called from inside the event-
// dispatching thread.  This is necessary because the main function is not
// operating in the event-dispatching thread.  See the main function for more
// info.
//

private static void createAndShowGUI()
{

    //instantiate an object to create and handle the main window JFrame
    MainWindow mainWindow = new MainWindow();

    //set up the new object
    mainWindow.init();

}//end of Main::createAndShowGUI
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Main::main
//

public static void main(String[] args)
{

    //Schedule a job for the event-dispatching thread:
    //creating and showing this application's GUI.

    javax.swing.SwingUtilities.invokeLater(
            new Runnable() {
                @Override
                public void run() { createAndShowGUI(); } });

}//end of Main::main
//-----------------------------------------------------------------------------

}//end of class Main
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------

